# Sampling 2

This file is belong to Muestreo1.ipynb

In [1]:
#Importiing libraries
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [6]:
#First we load the original pandas DataFrames
train1=pd.read_csv('train_sample.csv')
test1=pd.read_csv('test_sample.csv')
test1_2=pd.read_csv('test2_sample.csv')

In [7]:
#Pritting train1
train1.head()

image_name  patient_id     sex  age_approx anatom_site_general_challenge  \
0  ISIC_1455822  IP_0660290    male        60.0                         torso   
1  ISIC_8142027  IP_7785592    male        35.0                     head/neck   
2  ISIC_4856299  IP_4711011    male        15.0                         torso   
3  ISIC_8307332  IP_1214216  female        60.0                         torso   
4  ISIC_9758861  IP_5152468  female        25.0               upper extremity   

  diagnosis benign_malignant  target  
0   unknown           benign       0  
1   unknown           benign       0  
2   unknown           benign       0  
3   unknown           benign       0  
4   unknown           benign       0

In [8]:
#Pritting test1
test1.head()

image_name  patient_id     sex  age_approx anatom_site_general_challenge  \
0  ISIC_1777292  IP_8534235  female        60.0                         torso   
1  ISIC_5798331  IP_4988871  female        35.0                         torso   
2  ISIC_2317042  IP_9013996  female        75.0                     head/neck   
3  ISIC_4230049  IP_3449666  female        45.0                         torso   
4  ISIC_6927840  IP_9086201  female        40.0                  oral/genital   

  diagnosis benign_malignant  target  
0   unknown           benign       0  
1   unknown           benign       0  
2   unknown           benign       0  
3  melanoma        malignant       1  
4  melanoma        malignant       1

In [9]:
#Pritting test1_2
test1_2.head()

image_name  patient_id     sex  age_approx anatom_site_general_challenge  \
0  ISIC_0384214  IP_3728091    male        50.0                         torso   
1  ISIC_6346989  IP_2636470  female        50.0                         torso   
2  ISIC_6537539  IP_0046310    male        45.0                         torso   
3  ISIC_0888084  IP_2618037  female        25.0                     head/neck   
4  ISIC_5196005  IP_7207550    male        55.0               upper extremity   

  diagnosis benign_malignant  target  
0     nevus           benign       0  
1   unknown           benign       0  
2     nevus           benign       0  
3   unknown           benign       0  
4   unknown           benign       0

# Creating test2.csv

In this section creats the test2.csv using train_sample.csv

In [10]:
train1.to_csv('test2.csv', index=False)

# Creating train2.csv

312 positives from test2_sample.csv 113 negatives from test_sample.csv and 615 from test2_sample.csv

In [11]:
#Positives from test2_sample.csv
pos=test1_2.query('target==1')

In [12]:
#print pos
pos.head()

image_name  patient_id     sex  age_approx  \
12   ISIC_0274382  IP_7600629    male        65.0   
197  ISIC_2412113  IP_2025600  female        45.0   
267  ISIC_4967586  IP_7517320    male        60.0   
302  ISIC_8892236  IP_2962626  female        35.0   
491  ISIC_5673518  IP_5552354    male        45.0   

    anatom_site_general_challenge diagnosis benign_malignant  target  
12                          torso  melanoma        malignant       1  
197               upper extremity  melanoma        malignant       1  
267               upper extremity  melanoma        malignant       1  
302               lower extremity  melanoma        malignant       1  
491               upper extremity  melanoma        malignant       1

In [13]:
print(pos['target'].count())

312


In [15]:
#Negatives from test2_sample.csv
neg1=test1_2.query('target==0')
#Selecting 615 randomly
neg1=neg1.sample(n=615)

In [16]:
neg1['target'].count()

615

In [17]:
#Negatives from test2_sample.csv
neg2=test1.query('target==0')

In [18]:
neg2['target'].count()

113

In [19]:
#Appending
train2=pos
train2=train2.append(neg1)
train2=train2.append(neg2)

In [20]:
train2['target'].count()

1040

In [21]:
#SHUFFLING DATAFRAME train2
train2=train2.sample(frac=1).reset_index(drop=True)

In [22]:
train2['target'].count()

1040

In [23]:
#Saving train2.csv
train2.to_csv('train2.csv', index=False)

# Creating train3.csv

312 positives from test2_sample.csv, 40 positives from test_sample.csv, 113 negatives from test_sample.csv and 239 from test2_sample.csv

In [26]:
pos1=pos

In [27]:
pos2=test1.query('target==1')

In [29]:
#Negatives from test_sample.csv
neg3=neg2

In [31]:
#Negatives from test2_sample.csv
neg4=test1_2.query('target==0')
neg4=neg4.sample(n=239)

In [33]:
#Appending
train3=pos1
train3=train3.append(pos2)
train3=train3.append(neg3)
train3=train3.append(neg4)

In [35]:
train3['target'].count()

704

In [36]:
#SHUFFLING DATAFRAME train3
train3=train3.sample(frac=1).reset_index(drop=True)

In [37]:
#Saving train3.csv
train3.to_csv('train3.csv', index=False)